lessons:
  target: production
  outputs:
   production:
      dataset: dbt_production
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: User
      method: oauth
      priority: interactive
      project: polished-cocoa-431704-m8
      threads: 60
      type: bigquery
